### ISSUE TITLE
The default node package manager points to another module for 'ngx-markdown-editor'

### ISSUE THREAD

**Issue by andreimarcut** [mdefy/ngx-markdown-editor#1]
There is another project that is published on nodejs.com under the same id `ngx-markdown-editor`, see [https://www.npmjs.com/package/ngx-markdown-editor](https://www.npmjs.com/package/ngx-markdown-editor)

Using a default npm installation, I am unable to install this from the public package repository based on the instructions from the README. Instead, as a workaround, I clonef the repo and linkrf it as a local package.

**Comment by lenardfunk** [comment]
I'm so sorry... Yes, unfortunately the plain package name was already taken. For this library, it is `npm i @mdefy/ngx-markdown-editor`.

Thank you for the hint! The instructions are corrected now!
